### ISSUE TITLE
Is this project Dead?

### ISSUE THREAD

**Issue by hamzashahid-blit** [jcguu95/stumpwm-dynamic-float#1]
I was wondering as it has been 7 months since the last commit. I don't really understand how to use this library much (Not that I put a lot of effort into understanding either). Thanks.

Regards,
Hamza Shahid

**Comment by jcguu95** [comment]
I've been using this for 1 year and 4 months, and are very happy with it. It's very stable for me, so I didn't update it for a while. Please check the documentation and feel free to let me know which part it doesn't make sense to you. I'm glad to help!

Sadly though.. the video presentations won't come out soon. I'm quite busy recently. That said, you can check what it's doing in animation [here](https://www.reddit.com/r/lisp/comments/nb87hn/floating_dynamic_tiling_stumpwm_a_window_manager/).

**Comment by hamzashahid-blit** [comment]
Hi,
Thanks for answering. Very cool to hear that :smile:. Will read the documentation very soon.

Regards,
Hamza Shahid
